services:
  web:
    image: nginx:latest
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/templates/default.conf.template
    working_dir: /var/www
    links:
      - php
    ports:
      - 8081:80
  php:
    build: .
    links:
      - authors_db
    volumes:
      - .:/var/www
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
  authors_db:
    image: mysql:8.0
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - authors_db:/var/lib/mysql

volumes:
  authors_db:
  
networks:
  default:
    name: library-net
    external: true
